ERROR:root:[!] Failed to find the file.hosaas
Traceback (most recent call last):
  File "/home/kenan/Documents/AutoVN/cli.py", line 46, in do_build
    self.topo = Topology(template_file=cmds[0])
  File "/home/kenan/Documents/AutoVN/topo.py", line 31, in __init__
    raise Exception("[!] Failed to find the file." + template_file)
Exception: [!] Failed to find the file.hosaas
2020-09-12 17:08:24,840, ERROR, root, name 'Print' is not defined
Traceback (most recent call last):
  File "/home/kenan/Documents/AutoVN/cli.py", line 49, in do_build
    self.topo = Topology()
  File "/home/kenan/Documents/AutoVN/topo.py", line 30, in __init__
    self.networks, self.hosts = Template(template_file).parse()
  File "/home/kenan/Documents/AutoVN/template.py", line 32, in parse
    self.read_networks()
  File "/home/kenan/Documents/AutoVN/template.py", line 68, in read_networks
    self.networks[network] = Network(values["netaddr"], values["dhcplower"], values["dhcpupper"])
  File "/home/kenan/Documents/AutoVN/network.py", line 26, in __init__
    self.create()
  File "/home/kenan/Documents/AutoVN/network.py", line 113, in create
    Print.print_success("Created network " + self.netname)
NameError: name 'Print' is not defined
2020-09-12 17:12:05,032, ERROR, root, can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "/home/kenan/Documents/AutoVN/cli.py", line 139, in do_destroy
    self.topo.destroy()
  File "/home/kenan/Documents/AutoVN/topo.py", line 103, in destroy
    thread.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/kenan/Documents/AutoVN/network.py", line 151, in destroy
    Print.print_success("Destroyed network " + self.netname)
TypeError: can only concatenate str (not "NoneType") to str
2020-09-12 17:15:13,877, ERROR, root, can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "/home/kenan/Documents/AutoVN/cli.py", line 139, in do_destroy
    self.topo.destroy()
  File "/home/kenan/Documents/AutoVN/topo.py", line 103, in destroy
    thread.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/kenan/Documents/AutoVN/network.py", line 151, in destroy
    Print.print_success("Destroyed network ")
TypeError: can only concatenate str (not "NoneType") to str
